### PR TITLE
Add support to designate models and enums as internal

### PR DESCRIPTION
**Pull request by tjprescott**
Adds support to simultaneously rename models and designate them as `internal` in order to support convenience layers.

For example, say I have model `Widget` and I want to replace it with a customized model.

`autorest swagger.json --swift ... --generate-as-internal Widget=WidgetImpl`

or, better yet, add to your readme.md:

```yaml
remap-models: >
    Widget=WidgetImpl
    Foo=InternalFooWhatevs
```

This will result in Autorest generating the `Widget` struct with the name `WidgetImpl` *and* designating it and all of its members as `internal`. However, where this model is used inside autogenerated client methods and options, it will still generate with the `Widget` name, resulting in a broken reference. The intent is then that in your convenience layer you supply the customized model:

```swift
public struct Widget: Codable {
  init(from raw: WidgetImpl) {
    // convert WidgetImpl into Widget...
  }
}
```

This fixes the broken reference and should allow you to use the generated client without having to make a wrapper.

Closes #311. Fixes logic that is intended to prevent overwriting files that have already been written.

### CODE REVIEW

**Comment by knvsl** [comment]
@tjprescott I tried regenerating Chat with this branch but am not seeing the renames applied. I might be using the wrong syntax? I tried the following so far:

`CONFIG.MD:`
```yaml $(swift)
namespace: AzureCommunicationChat
remap-models: >
    CreateChatThreadResult=CreateChatThreadResultInternal
    CreateChatThreadRequest=CreateChatThreadRequestInternal
    ChatMessage=ChatMessageInternal
    ChatMessageContent=ChatMessageContentInternal
    ChatParticipant=ChatParticipantInternal
    ChatMessageReadReceipt=ChatMessageReadReceiptInternal
    ChatThreadProperties=ChatThreadPropertiesInternal
    CommunicationError=ChatError
```

Using above config as below (replacing placeholders with actual paths), where my local autorest is on the `feature/generateInternal` branch:
```
autorest CONFIG.md
--swift
--use=<PATH TO AUTOREST>/Documents/autorest.swift
--input-file=<PATH TO SWAGGER>/swagger.json
--output-folder=<PATH TO AZURE SDK>/azure-sdk-for-ios/sdk/communication/AzureCommunicationChat
```

Also tried using without a configuration file:

```
autorest
--swift
--use=<PATH TO AUTOREST>/autorest.swift
--input-file=<PATH TO SWAGGER>/swagger.json
--output-folder=<PATH TO AZURE SDK>/azure-sdk-for-ios/sdk/communication/AzureCommunicationChat
--remap-models ChatParticipant=ChatParticipantInternal
```

**Comment by tjprescott** [comment]
@knvsl if you are using command line directly, you have to specify `--remap-models="ChatParticipant=ChatParticipantInternal"` otherwise autorest will complain about "multiple configuration files".

When you switch to this branch, you probably also need to run `make install` first to ensure the updated templates are installed correctly.

**Comment by knvsl** [comment]
So I still am not seeing the changes applied, I feel I'm missing a step here. It's regenerating without error but I don't see the changes applied.

Here's what I am doing:
1. Checkout feature/generateInternal
2. on feature/generateInternal `npm run install`
3. My CONFIG.MD:
```yaml
namespace: AzureCommunicationChat
remap-models: >
    CreateChatThreadResult=CreateChatThreadResultInternal
    CreateChatThreadRequest=CreateChatThreadRequestInternal
    ChatMessage=ChatMessageInternal
    ChatMessageContent=ChatMessageContentInternal
    ChatParticipant=ChatParticipantInternal
    ChatMessageReadReceipt=ChatMessageReadReceiptInternal
    ChatThreadProperties=ChatThreadPropertiesInternal
    CommunicationError=ChatError
```
4. My swagger.json: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/communication/data-plane/Microsoft.CommunicationServicesChat/stable/2021-03-07/communicationserviceschat.json
5. Run following autorest command:
```
autorest 
  CONFIG.MD 
  --input-file=swagger.json
  --output-folder=/Users/kinovose/Documents/azure-sdk-for-ios/sdk/communication/AzureCommunicationChat
  --use=/Users/kinovose/Documents/autorest.swift
```

I double checked the CONFIG.MD is being applied, because if I revert the contents to contain the directives I had they are applied

**Comment by tjprescott** [comment]
@knvsl after step 1 you have to run `make install` in your autorest repo. This is the only the updated templates will get installed.

**Comment by knvsl** [comment]
@tjprescott `npm run install` runs `make install`, but I also tried running `make install` directly & don't see a difference.

**Comment by tjprescott** [comment]
@knvsl, can you do two things:

1) On line 30 fo `main.swift`, change the `logLevel` to `LogLevel.info`
2) Run your command. In you `Documents` folder should be a file called `autorest-swift-debug.log`. Open that and ensure that your config settings are in the logs under `Autorest Configuration`.

**Comment by knvsl** [comment]
@tjprescott Interesting, after changing the log level and re-running I do NOT see my config settings. I see there is an error as well, but autorest is still completing the code generation (the renames just aren't applied):

```
AutorestSwift.default (INFO) Autorest Configuration: {

}
AutorestSwift.default (WARN) Discrepancies found in round-tripped code model. Error saving files: Error Domain=NSCocoaErrorDomain Code=4 "The folder “before.json” doesn’t exist." UserInfo={NSFilePath=/var/folders/vd/bv1hsvk55_9_fvkmz017mmqm0000gn/T/7B24CC80-FE19-424F-9CCE-CF013D1BDB45/before.json, NSUserStringVariant=Folder, NSUnderlyingError=0x7f8bd54d2480 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
AutorestSwift.default (INFO) Generating code at: /var/folders/vd/bv1hsvk55_9_fvkmz017mmqm0000gn/T/7B24CC80-FE19-424F-9CCE-CF013D1BDB45/AzureCommunicationChat
AutorestSwift.default (INFO) Base URL: /var/folders/vd/bv1hsvk55_9_fvkmz017mmqm0000gn/T/7B24CC80-FE19-424F-9CCE-CF013D1BDB45/AzureCommunicationChat

```

**Comment by tjprescott** [comment]
@knvsl you don't need to worry about the round-trip error. However, the fact that it is showing the Autorest Configuration means you are running on the branch. I just don't see anything that would indicate why it's not parsing the setting. What if you pass `--remap-models="..."` via the command line?

**Comment by knvsl** [comment]
I was one commit behind on the branch, pulled latest and I am able to see the changes applied **when using the flag on the command line**, I'm unable to get the CONFIG.md working though

Here's what works for me (for input file I'm referencing the swagger published to the specs repo):
```
autorest
--swift
--use=/Users/kinovose/Documents/autorest.swift
--input-file=https://github.com/Azure/azure-rest-api-specs/blob/master/specification/communication/data-plane/Microsoft.CommunicationServicesChat/stable/2021-03-07/communicationserviceschat.json
--output-folder=/Users/kinovose/Documents/azure-sdk-for-ios/sdk/communication/AzureCommunicationChat
--namespace=AzureCommunicationChat
--remap-models="CreateChatThreadResult=CreateChatThreadResultInternal CreateChatThreadRequest=CreateChatThreadRequestInternal ChatMessage=ChatMessageInternal ChatMessageContent=ChatMessageContentInternal ChatParticipant=ChatParticipantInternal ChatMessageReadReceipt=ChatMessageReadReceiptInternal ChatThreadProperties=ChatThreadPropertiesInternal CommunicationError=ChatError"
```

**Pull request merged**
