### PR TITLE
Support UnixTime  test cases

### PR DESCRIPTION
**Pull request by sacheu**
* Add unixTimeBody strategy to decode UnixTime from data
* Refactor  templates/OperationResponseDataSnippet.stencil to break up into templates/OperationResponseStatusCodeDeclareSnippet.stencil and templates/OperationResponseDataSnippet.stencil
* Checked in regenerated code.

### CODE REVIEW

**Review by tjprescott — COMMENTED** [review]
Does this not require the adjustment to AzureCore?

**Comment by sacheu** [comment]
> Does this not require the adjustment to AzureCore?

Yes, we still need to change AzureCore to get these UnixTime test cases to work. I have filed an issue for this https://github.com/Azure/azure-sdk-for-ios-pr/issues/25

**Comment by tjprescott** [comment]
The change to AzureCore has been merged, which should unblock this.

**Review by tjprescott — APPROVED** [review]
LGTM, just needs rebase

**Pull request merged**
